### ISSUE TITLE
Invalid link in https://ribir.org/docs/get_started/quick_start#closure-and-fn_widget

### ISSUE THREAD

**Issue by Fidius-jko** [RibirX/ribir-website#13]
[Creating an application](https://ribir.org/docs/get_started/creating_an_application.md) does not exist.

![image](https://github.com/RibirX/ribir-website/assets/95738553/eb6b251e-e9eb-4ea3-8611-0361116e9379)

**Comment by M-Adoo** [comment]
Thanks for the report! 

The `Creating an Application` is renamed to [Try Ribir](https://ribir.org/docs/next/get_started/try_it).

I fixed the link in the [next](https://ribir.org/docs/next/get_started/try_it) version of the documentation.
